# # -*- coding: utf-8 -*-
# """Assignment_1_Pytorch_MNIST.ipynb
#
# Automatically generated by Colaboratory.
#
# Original file is located at
#     https://colab.research.google.com/drive/1i9KpbQyFU4zfq8zLLns8a2Kd8PRMGsaZ
#
# Overall structure:
#
# 1) Set Pytorch metada
# - seed
# - tensorflow output
# - whether to transfer to gpu (cuda)
#
# 2) Import data
# - download data
# - create data loaders with batchsie, transforms, scaling
#
# 3) Define Model architecture, loss and optimizer
#
# 4) Define Test and Training loop
#     - Train:
#         a. get next batch
#         b. forward pass through model
#         c. calculate loss
#         d. backward pass from loss (calculates the gradient for each parameter)
#         e. optimizer: performs weight updates
#
# 5) Perform Training over multiple epochs:
#     Each epoch:
#     - call train loop
#     - call test loop
#
# Acknowledgments:https://github.com/motokimura/pytorch_tensorboard/blob/master/main.py
# """
#
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# import torch.optim as optim
# from torchvision import datasets, transforms
#
# from torch.utils.tensorboard import SummaryWriter
# from datetime import datetime
# import os
# from pathlib import Path
#
# batch_size = 64
# test_batch_size = 1000
# epochs = 10
# lr = 0.01
# try_cuda = True
# seed = 1000
# logging_interval = 10 # how many batches to wait before logging
# logging_dir = None
#
# # 1) setting up the logging
# if logging_dir is None:
#     logging_dir = Path('./logs') / datetime.now().strftime('%Y%m%d-%H%M%S')
# writer = SummaryWriter(log_dir=str(logging_dir))
#
# #deciding whether to send to the cpu or not if available
# if torch.cuda.is_available() and try_cuda:
#     cuda = True
#     torch.cuda.mnaual_seed(seed)
# else:
#     cuda = False
#     torch.manual_seed(seed)
#
# # Setting up data
# transform = transforms.Compose([
#     transforms.ToTensor(),
#     transforms.Normalize((0.1307,), (0.3081,))
# ])
#
# # Setting up data loaders
# train_loader = torch.utils.data.DataLoader(
#     datasets.MNIST('./data', train=True, download=True, transform=transform),
#     batch_size=batch_size, shuffle=True)
#
# test_loader = torch.utils.data.DataLoader(
#     datasets.MNIST('./data', train=False, download=True, transform=transform),
#     batch_size=test_batch_size, shuffle=False)
#
# # Defining Architecture,loss and optimizer
# class Net(nn.Module):
#     def __init__(self):
#
#         super(Net, self).__init__()
#         # First convolutional layer: 1 input channel, 32 output channels, 5x5 kernel
#         self.conv1 = nn.Conv2d(1, 32, kernel_size=5)
#         # Second convolutional layer: 32 input channels, 64 output channels, 5x5 kernel
#         self.conv2 = nn.Conv2d(32, 64, kernel_size=5)
#         # Fully connected layer: input features calculated from conv layers, 1024 output features
#         self.fc1 = nn.Linear(64 * 4 * 4, 1024)
#         # Output layer: 1024 input features, 10 classes
#         self.fc2 = nn.Linear(1024, 10)
#
#     def forward(self, x):
#         # Apply first convolutional layer, ReLU activation, and max pooling
#         x = F.relu(F.max_pool2d(self.conv1(x), 2))
#         # Apply second convolutional layer, ReLU activation, and max pooling
#         x = F.relu(F.max_pool2d(self.conv2(x), 2))
#         # Flatten the tensor for the fully connected layer
#         x = x.view(-1, 64 * 4 * 4)
#         # Apply first fully connected layer with ReLU activation
#         x = F.relu(self.fc1(x))
#         # Output layer (raw logits)
#         x = self.fc2(x)
#         return x
#
# # Instantiate the model
# model = Net()
# if cuda:
#     model.cuda()
#
# # Use an Adam optimizer
# optimizer = optim.Adam(model.parameters(), lr=0.001)
#
#
# # Defining the test and trainig loops
# eps=1e-13
#
# def train(epoch):
#     model.train()
#
#     criterion = nn.CrossEntropyLoss()
#     correct = 0
#     total = 0
#
#     for batch_idx, (data, target) in enumerate(train_loader):
#         if cuda:
#             data, target = data.cuda(), target.cuda()
#         optimizer.zero_grad()
#         output = model(data)
#         loss = criterion(output, target)
#         loss.backward()
#         optimizer.step()
#
#         # Calculate training accuracy
#         pred = output.argmax(dim=1, keepdim=True)
#         correct += pred.eq(target.view_as(pred)).sum().item()
#         total += target.size(0)
#
#         if batch_idx % logging_interval == 0:
#             accuracy = 100. * correct / total
#             print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} '
#                   f'({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item():.6f}\tAccuracy: {accuracy:.2f}%')
#             n_iter = (epoch - 1) * len(train_loader) + batch_idx
#             writer.add_scalar('Loss/train', loss.item(), n_iter)
#             writer.add_scalar('Accuracy/train', accuracy, n_iter)
#
#     # Log model parameters to TensorBoard at every epoch
#     for name, param in model.named_parameters():
#         layer, attr = os.path.splitext(name)
#         attr = attr[1:]
#         writer.add_histogram(
#             f'{layer}/{attr}',
#             param.clone().cpu().data.numpy(),
#             n_iter)
#
#
#
# def test(epoch):
#     model.eval()
#     test_loss = 0
#     correct = 0
#     #criterion = nn.CrossEntropyLoss()
#
#     #criterion = nn.CrossEntropyLoss(size_average = False)
#     criterion = nn.CrossEntropyLoss(reduction='sum')  # Sum up batch loss
#
#     with torch.no_grad():
#         for data, target in test_loader:
#             if cuda:
#                 data, target = data.cuda(), target.cuda()
#             output = model(data)
#             test_loss += criterion(output, target).item()  # Accumulate loss
#             pred = output.argmax(dim=1, keepdim=True)      # Get the index of the max log-probability
#             correct += pred.eq(target.view_as(pred)).sum().item()
#
#     test_loss /= len(test_loader.dataset)
#     test_accuracy = 100. * correct / len(test_loader.dataset)
#     # Print the performance
#     print(f'\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} '
#           f'({test_accuracy:.0f}%)\n')
#
#     # Log test/loss and test/accuracy to TensorBoard at every epoch
#     # Log the performance
#     n_iter = epoch * len(train_loader)
#     writer.add_scalar('Loss/test', test_loss, n_iter)
#     writer.add_scalar('Accuracy/test', test_accuracy, n_iter)
#
# # Training loop
# # Running training and testing over epochs
# for epoch in range(1, epochs + 1):
#     train(epoch)
#     test(epoch)
#     # Log model parameters to TensorBoard at every epoch
#     for name, param in model.named_parameters():
#         writer.add_histogram(name, param.clone().cpu().data.numpy(), epoch)
#
# writer.close()
#
# # Commented out IPython magic to ensure Python compatibility.
# """
# #https://stackoverflow.com/questions/55970686/tensorboard-not-found-as-magic-function-in-jupyter
#
# #seems to be working in firefox when not working in Google Chrome when running in Colab
# #https://stackoverflow.com/questions/64218755/getting-error-403-in-google-colab-with-tensorboard-with-firefox
#
#
# # %load_ext tensorboard
# # %tensorboard --logdir [dir]
#
# """

import torch
import torch.nn as nn
import torch.nn.init as init
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

from torch.utils.tensorboard import SummaryWriter
from datetime import datetime
import os
from pathlib import Path
import numpy as np

batch_size = 64
test_batch_size = 1000
epochs = 10
lr = 0.001
try_cuda = True
seed = 1000
logging_interval = 100  # Log every 100 iterations
logging_dir = None

# 1) setting up the logging
if logging_dir is None:
    logging_dir = Path('./logs') / datetime.now().strftime('%Y%m%d-%H%M%S')
writer = SummaryWriter(log_dir=str(logging_dir))

# Deciding whether to send to the cpu or not if available
if torch.cuda.is_available() and try_cuda:
    cuda = True
    torch.cuda.manual_seed(seed)
else:
    cuda = False
    torch.manual_seed(seed)

# Setting up data
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# Create training and validation split
validation_split = 0.1
shuffle_dataset = True
random_seed = seed

# Dataset
dataset = datasets.MNIST('./data', train=True, download=True, transform=transform)
dataset_size = len(dataset)
indices = list(range(dataset_size))
split = int(np.floor(validation_split * dataset_size))

if shuffle_dataset:
    np.random.seed(random_seed)
    np.random.shuffle(indices)

train_indices, val_indices = indices[split:], indices[:split]

# Create data samplers and loaders
train_sampler = torch.utils.data.SubsetRandomSampler(train_indices)
valid_sampler = torch.utils.data.SubsetRandomSampler(val_indices)

train_loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, sampler=train_sampler)
valid_loader = torch.utils.data.DataLoader(dataset, batch_size=test_batch_size, sampler=valid_sampler)

test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('./data', train=False, download=True, transform=transform),
    batch_size=test_batch_size, shuffle=False)


# Defining Architecture,loss and optimizer
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # First convolutional layer
        self.conv1 = nn.Conv2d(1, 32, kernel_size=5)
        # Second convolutional layer
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5)
        # Fully connected layers
        self.fc1 = nn.Linear(64 * 4 * 4, 1024)
        self.fc2 = nn.Linear(1024, 10)

        # Apply Xavier initialization to the weights of each layer
        init.xavier_uniform_(self.conv1.weight)
        init.xavier_uniform_(self.conv2.weight)
        init.xavier_uniform_(self.fc1.weight)
        init.xavier_uniform_(self.fc2.weight)

        # also initialize the biases
        if self.conv1.bias is not None:
            init.constant_(self.conv1.bias, 0)
        if self.conv2.bias is not None:
            init.constant_(self.conv2.bias, 0)
        if self.fc1.bias is not None:
            init.constant_(self.fc1.bias, 0)
        if self.fc2.bias is not None:
            init.constant_(self.fc2.bias, 0)

    def forward(self, x):
        # Net input and activations for conv1
        self.z1 = self.conv1(x)
        # self.a1 = F.relu(self.z1)
        self.a1 = F.leaky_relu(self.z1, negative_slope=0.01)
        self.a1p = F.max_pool2d(self.a1, 2)

        # Net input and activations for conv2
        self.z2 = self.conv2(self.a1p)
        # self.a2 = F.relu(self.z2)
        self.a2 = F.leaky_relu(self.z2, negative_slope=0.01)
        self.a2p = F.max_pool2d(self.a2, 2)

        # Flatten
        x = self.a2p.view(-1, 64 * 4 * 4)

        # Net input and activations for fc1
        self.z3 = self.fc1(x)
        # self.a3 = F.relu(self.z3)
        self.a3 = F.leaky_relu(self.z3, negative_slope=0.01)

        # Net input for output layer
        self.z4 = self.fc2(self.a3)

        return self.z4


# Instantiate the model
model = Net()
if cuda:
    model.cuda()

# Use an Adam optimizer
# optimizer = optim.Adam(model.parameters(), lr=lr)
# Use a SGD optimizer
optimizer = optim.SGD(model.parameters(), lr=lr)



def train(epoch):
    model.train()
    criterion = nn.CrossEntropyLoss()
    correct = 0
    total = 0

    for batch_idx, (data, target) in enumerate(train_loader):
        if cuda:
            data, target = data.cuda(), target.cuda()
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()

        # Calculate training accuracy
        pred = output.argmax(dim=1, keepdim=True)
        correct += pred.eq(target.view_as(pred)).sum().item()
        total += target.size(0)

        n_iter = (epoch - 1) * len(train_loader) + batch_idx

        if batch_idx % logging_interval == 0:
            accuracy = 100. * correct / total
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.sampler)} '
                  f'({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item():.6f}\tAccuracy: {accuracy:.2f}%')

            # Log loss and accuracy
            writer.add_scalar('Loss/train', loss.item(), n_iter)
            writer.add_scalar('Accuracy/train', accuracy, n_iter)

            # Log weights, biases, and gradient statistics
            for name, param in model.named_parameters():
                # Log weights statistics
                writer.add_histogram(f'{name}_weights', param.clone().cpu().data.numpy(), n_iter)
                writer.add_scalar(f'{name}_weights_min', param.min().item(), n_iter)
                writer.add_scalar(f'{name}_weights_max', param.max().item(), n_iter)
                writer.add_scalar(f'{name}_weights_mean', param.mean().item(), n_iter)
                writer.add_scalar(f'{name}_weights_std', param.std().item(), n_iter)

                # Log gradient statistics
                if param.grad is not None:
                    writer.add_histogram(f'{name}_grad', param.grad.clone().cpu().data.numpy(), n_iter)
                    writer.add_scalar(f'{name}_grad_min', param.grad.min().item(), n_iter)
                    writer.add_scalar(f'{name}_grad_max', param.grad.max().item(), n_iter)
                    writer.add_scalar(f'{name}_grad_mean', param.grad.mean().item(), n_iter)
                    writer.add_scalar(f'{name}_grad_std', param.grad.std().item(), n_iter)

            # Log net inputs and activations statistics
            for layer, data in zip(['z1', 'a1', 'a1p', 'z2', 'a2', 'a2p', 'z3', 'a3', 'z4'],
                                   [model.z1, model.a1, model.a1p, model.z2, model.a2, model.a2p, model.z3, model.a3, model.z4]):
                writer.add_histogram(f'{layer}_hist', data.clone().cpu().data.numpy(), n_iter)
                writer.add_scalar(f'{layer}_min', data.min().item(), n_iter)
                writer.add_scalar(f'{layer}_max', data.max().item(), n_iter)
                writer.add_scalar(f'{layer}_mean', data.mean().item(), n_iter)
                writer.add_scalar(f'{layer}_std', data.std().item(), n_iter)

        # Validate and test every 1100 iterations
        if n_iter % 1100 == 0 and n_iter > 0:
            validate(epoch, n_iter)
            test(epoch, n_iter)

def validate(epoch, n_iter):
    model.eval()
    val_loss = 0
    correct = 0
    criterion = nn.CrossEntropyLoss(reduction='sum')
    with torch.no_grad():
        for data, target in valid_loader:
            if cuda:
                data, target = data.cuda(), target.cuda()
            output = model(data)
            val_loss += criterion(output, target).item()
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

    val_loss /= len(valid_loader.sampler)  # Use the correct denominator
    val_accuracy = 100. * correct / len(valid_loader.sampler)
    print(f'\nValidation set: Average loss: {val_loss:.4f}, Accuracy: {correct}/{len(valid_loader.sampler)} '
          f'({val_accuracy:.2f}%)\n')

    # Log validation loss and accuracy
    writer.add_scalar('Loss/validation', val_loss, n_iter)
    writer.add_scalar('Accuracy/validation', val_accuracy, n_iter)

def test(epoch, n_iter):
    model.eval()
    test_loss = 0
    correct = 0
    criterion = nn.CrossEntropyLoss(reduction='sum')
    with torch.no_grad():
        for data, target in test_loader:
            if cuda:
                data, target = data.cuda(), target.cuda()
            output = model(data)
            test_loss += criterion(output, target).item()  # Sum up batch loss
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    test_accuracy = 100. * correct / len(test_loader.dataset)
    print(f'\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} '
          f'({test_accuracy:.2f}%)\n')

    # Log test loss and accuracy
    writer.add_scalar('Loss/test', test_loss, n_iter)
    writer.add_scalar('Accuracy/test', test_accuracy, n_iter)


# Training loop
for epoch in range(1, epochs + 1):
    train(epoch)
    validate(epoch, epoch * len(train_loader))  # Log at end of each epoch
    test(epoch, epoch * len(train_loader))  # Log at end of each epoch

writer.close()